/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicineis;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prashant R. Rai
 */
public class MedicineIS extends javax.swing.JFrame {

    ArrayList<MedicineTableData> Mdata = new ArrayList<MedicineTableData>();
    ArrayList<String> CateNames = new ArrayList<>();

    /**
     * Creates new form MedicineFront
     */
    public MedicineIS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrontFrame = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ButLogin = new javax.swing.JButton();
        Head1 = new javax.swing.JLabel();
        Passwordlbl = new javax.swing.JLabel();
        Loginlbl = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JPasswordField();
        UserNameTxt = new javax.swing.JTextField();
        Head2 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        TablePanel = new javax.swing.JPanel();
        database = new javax.swing.JScrollPane();
        DatabaseTable = new javax.swing.JTable();
        SearchPanel = new javax.swing.JPanel();
        SearchPriceTxt = new javax.swing.JTextField();
        ButSearchPrice = new javax.swing.JButton();
        HeadTitle = new javax.swing.JLabel();
        ButSort = new javax.swing.JButton();
        ButDelete = new javax.swing.JButton();
        InputPanel = new javax.swing.JPanel();
        SerialNumlbl = new javax.swing.JLabel();
        SerialNumTxt = new javax.swing.JTextField();
        Namelbl = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        Pricelbl = new javax.swing.JLabel();
        PriceTxt = new javax.swing.JTextField();
        Mfglbl = new javax.swing.JLabel();
        MfgTxt = new javax.swing.JTextField();
        Explbl = new javax.swing.JLabel();
        ExpTxt = new javax.swing.JTextField();
        Categorylbl = new javax.swing.JLabel();
        CategoryBox = new javax.swing.JComboBox<>();
        ButCategory = new javax.swing.JButton();
        ButAdd = new javax.swing.JButton();
        ButClear = new javax.swing.JButton();
        Typelbl = new javax.swing.JLabel();
        TypeTxt = new javax.swing.JTextField();
        MenuB = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenuI = new javax.swing.JMenuItem();
        ExitMenuI = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        HelpMenuI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medicine IS");

        FrontFrame.setVisible(true);

        ButLogin.setBackground(new java.awt.Color(250, 250, 250));
        ButLogin.setText("LOG IN");
        ButLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLoginActionPerformed(evt);
            }
        });

        Head1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Head1.setForeground(new java.awt.Color(80, 80, 80));
        Head1.setText("[  WELCOME TO  ]");

        Passwordlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Passwordlbl.setText("Password:");

        Loginlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Loginlbl.setText("UserName:");

        PasswordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTxtActionPerformed(evt);
            }
        });

        UserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTxtActionPerformed(evt);
            }
        });

        Head2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Head2.setForeground(new java.awt.Color(80, 80, 80));
        Head2.setText("MEDICINE INFORMATION SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(Head1))
                    .addComponent(Head2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(Loginlbl)
                        .addGap(73, 73, 73)
                        .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Passwordlbl)
                        .addGap(70, 70, 70)
                        .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(ButLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Head1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Head2)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Loginlbl)
                    .addComponent(UserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Passwordlbl))
                    .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(ButLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout FrontFrameLayout = new javax.swing.GroupLayout(FrontFrame);
        FrontFrame.setLayout(FrontFrameLayout);
        FrontFrameLayout.setHorizontalGroup(
            FrontFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrontFrameLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        FrontFrameLayout.setVerticalGroup(
            FrontFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrontFrameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        MainPanel.setVisible(false);
        MainPanel.setBackground(new java.awt.Color(250, 250, 250));

        TablePanel.setBackground(new java.awt.Color(250, 250, 250));

        DatabaseTable.setBackground(new java.awt.Color(240, 240, 240));
        DatabaseTable.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        DatabaseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SN", "Name", "Type", "Category", "Price", "Mfg Date", "Exp Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        database.setViewportView(DatabaseTable);

        SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Based On Price", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 13), new java.awt.Color(80, 80, 80))); // NOI18N

        SearchPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPriceTxtActionPerformed(evt);
            }
        });

        ButSearchPrice.setBackground(new java.awt.Color(250, 250, 250));
        ButSearchPrice.setText("Search");
        ButSearchPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSearchPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButSearchPrice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addComponent(ButSearchPrice)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(SearchPriceTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        HeadTitle.setBackground(new java.awt.Color(250, 250, 250));
        HeadTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        HeadTitle.setForeground(new java.awt.Color(80, 80, 80));
        HeadTitle.setText("MEDICINE INFORMATION SYSTEM");

        ButSort.setText("Sort Table");
        ButSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSortActionPerformed(evt);
            }
        });

        ButDelete.setText("Delete Table");
        ButDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TablePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(database))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TablePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(HeadTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButSort)
                .addGap(29, 29, 29)
                .addComponent(ButDelete)
                .addGap(41, 41, 41))
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TablePanelLayout.createSequentialGroup()
                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TablePanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(HeadTitle))
                    .addGroup(TablePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(database, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButSort, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INPUT SECTION", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 13), new java.awt.Color(80, 80, 80))); // NOI18N

        SerialNumlbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        SerialNumlbl.setForeground(new java.awt.Color(80, 80, 80));
        SerialNumlbl.setText("Serial Number:");

        SerialNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialNumTxtActionPerformed(evt);
            }
        });

        Namelbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Namelbl.setForeground(new java.awt.Color(80, 80, 80));
        Namelbl.setText("Name:");

        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });

        Pricelbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Pricelbl.setForeground(new java.awt.Color(80, 80, 80));
        Pricelbl.setText("Price:");

        PriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceTxtActionPerformed(evt);
            }
        });

        Mfglbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Mfglbl.setForeground(new java.awt.Color(80, 80, 80));
        Mfglbl.setText("Mfg Date:");

        MfgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfgTxtActionPerformed(evt);
            }
        });

        Explbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Explbl.setForeground(new java.awt.Color(80, 80, 80));
        Explbl.setText("Exp Date:");

        ExpTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpTxtActionPerformed(evt);
            }
        });

        Categorylbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Categorylbl.setForeground(new java.awt.Color(80, 80, 80));
        Categorylbl.setText("Category:");

        CategoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Antibacterials", "Antifungal Medicines", "Medicines Used in Shock", "Antiepileptics/Anticonvulsants", "Hormones and Antihormones" }));

        ButCategory.setBackground(new java.awt.Color(250, 250, 250));
        ButCategory.setText("Category based search");
        ButCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCategoryActionPerformed(evt);
            }
        });

        ButAdd.setBackground(new java.awt.Color(250, 250, 250));
        ButAdd.setText("Add");
        ButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAddActionPerformed(evt);
            }
        });

        ButClear.setBackground(new java.awt.Color(250, 250, 250));
        ButClear.setText("Clear");
        ButClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButClearActionPerformed(evt);
            }
        });

        Typelbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Typelbl.setForeground(new java.awt.Color(80, 80, 80));
        Typelbl.setText("Type:");

        TypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Categorylbl)
                    .addComponent(SerialNumlbl)
                    .addComponent(Namelbl)
                    .addComponent(Typelbl))
                .addGap(33, 33, 33)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Mfglbl))
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Explbl)
                                    .addGroup(InputPanelLayout.createSequentialGroup()
                                        .addComponent(SerialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(148, 148, 148)
                                        .addComponent(Pricelbl)))))
                        .addGap(50, 50, 50)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MfgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(ButAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(ButClear, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InputPanelLayout.createSequentialGroup()
                                .addComponent(CategoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(ButCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SerialNumlbl)
                    .addComponent(SerialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pricelbl))
                .addGap(21, 21, 21)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namelbl)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mfglbl)
                    .addComponent(MfgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Explbl)
                    .addComponent(ExpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Typelbl)
                    .addComponent(TypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categorylbl)
                    .addComponent(CategoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(ButClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        FileMenu.setText("File");

        OpenMenuI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenMenuI.setText("Open");
        OpenMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuIActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenuI);

        ExitMenuI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ExitMenuI.setText("Exit");
        ExitMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuIActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenuI);

        MenuB.add(FileMenu);

        HelpMenu.setText("Help");

        HelpMenuI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        HelpMenuI.setText("Help");
        HelpMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuIActionPerformed(evt);
            }
        });
        HelpMenu.add(HelpMenuI);

        MenuB.add(HelpMenu);

        setJMenuBar(MenuB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FrontFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(FrontFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuIActionPerformed
        readCSV();
    }//GEN-LAST:event_OpenMenuIActionPerformed

    private void SearchPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchPriceTxtActionPerformed
    
    
    //Search price button
    private void ButSearchPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSearchPriceActionPerformed
        String priceAmt = SearchPriceTxt.getText().trim();
        
        if(priceAmt.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please enter the price of the medicine you want to search!","Search",2);
        }
        else{
            try{
                int searchedPrice = Integer.parseInt(priceAmt);
                selectionSort();
                int searchResult = binarySearch(Mdata, 0, Mdata.size()-1, searchedPrice);
                if (searchResult == -1){
                    JOptionPane.showMessageDialog(this, "Sorry, medicine of price Rs." + searchedPrice + " was not found.", "Message", 1);
                    return;
                }
                else{
                    JOptionPane.showMessageDialog(this, "SerialNo= " + Mdata.get(searchResult).getSerialNumTxt() + "\nName= " +
                    Mdata.get(searchResult).getNameTxt() + "\nType= " + Mdata.get(searchResult).getTypeTxt() + "\nCategory= " + Mdata.get(searchResult).getCategoryBox()
                    + "\nPrice=" + Mdata.get(searchResult).getPriceTxt() + "\nMfg Date=" + Mdata.get(searchResult).getMfgTxt() + "\nExpiry date=" + Mdata.get(searchResult).getExpTxt(), "Message", 1);
                    SearchPriceTxt.setText("");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,"Exception occured","Error",0);
            }
        }
    }//GEN-LAST:event_ButSearchPriceActionPerformed

    private void SerialNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SerialNumTxtActionPerformed

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed

    private void PriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceTxtActionPerformed

    private void MfgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfgTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MfgTxtActionPerformed

    private void ExpTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpTxtActionPerformed
    
    
    //Category based search button
    private void ButCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCategoryActionPerformed
        String category = CategoryBox.getSelectedItem().toString();
        int countCat = countCategory();
        
        if (CategoryBox.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please You have to Choose atleast one category", "Category Based Searching",0);
        }else if (countCat == 0){
            JOptionPane.showMessageDialog(this, "Medicine of this category is not found", "Category Based Searching", 1);
        }else if (countCat == 1){
            JOptionPane.showMessageDialog(this, "Only one medicine of " + category + " category \nNamed = " + CateNames + "is available.", "Category Based Searching", 1);
            CateNames.clear();
        }
        else{
            JOptionPane.showMessageDialog(this,"There are " + countCat + " medicine of " + category + " category \nNamed = " + CateNames, "Category Based Searching", 1);
            CateNames.clear();
        }
    }//GEN-LAST:event_ButCategoryActionPerformed
    
    
    //Help menu
    private void HelpMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuIActionPerformed
        JOptionPane.showMessageDialog(this, "System version 1.1 \nUSERNAME & PASSWORD: You can use your username and password as admin for log in. \n\nOpen file: To open file containing all "
                + "the details of the medicines in the system \ndatabase you can either press 'ctrl + O' or go to menubar. \n\nExit: To exit you can either press 'Ctrl + E' as shortcut or go "
                + "to menu bar. \n\nCategory based search: First you need to select which category of medicine you are searching for then \nyou can search it based on thier category "
                + "with the help of button name 'Category based searched'.\n\nPrice based search: You can also search medicine based on their price. There is a price "
                + "\nbased search section from where you can do the searching. \n\nSort: There is a sorting button which sorts the data inside the table on the basis of "
                + "serial number of the medicine. \n\nDelete: When you open file and populate the table and if you want to clear the data from the table then you can \npress the button name 'Delete'."
                + "ADD: If you want to add other medicine details in the database/table then you can \nenter the details in input section and press 'ADD' button."
                + "\n\nClear: Clear button in the input section clears the data entered previously in the textfields."
                + "\n\n                                                      **THANK YOU FOR USING OUR SYSTEM**", "Help", 1);
    }//GEN-LAST:event_HelpMenuIActionPerformed
    
    
    //Clear button
    private void ButClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButClearActionPerformed





































        SerialNumTxt.setText("");
        NameTxt.setText("");
        TypeTxt.setText("");
        CategoryBox.setSelectedIndex(0);
        PriceTxt.setText("");
        MfgTxt.setText("");
        ExpTxt.setText("");
    }//GEN-LAST:event_ButClearActionPerformed
    
    
    //Method for counting Category index
    public int countCategory(){
        String category = CategoryBox.getSelectedItem().toString();
        int countCat = 0;
        
        for(MedicineTableData detail: Mdata){
            
            if (category.equals(detail.getCategoryBox())){
                CateNames.add(detail.getNameTxt());
                countCat++;
            }
        }
        return countCat;
    }
    
    
    //ADD button
    private void ButAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAddActionPerformed
        String SerialNo = SerialNumTxt.getText().trim();
        String Name = NameTxt.getText().trim();
        String Type = TypeTxt.getText().trim();
        String Category = CategoryBox.getSelectedItem().toString();
        String Price = PriceTxt.getText().trim();
        String Mfg = MfgTxt.getText().trim();
        String Exp = ExpTxt.getText().trim();
        int SerialNumber, Mdprice;
        
        DefaultTableModel dfm = (DefaultTableModel)DatabaseTable.getModel();
        String [] st = {SerialNo, Name,Type, Category, Price, Mfg, Exp};
        if(SerialNo.equals("") || Name.equals("") || Type.equals("") || CategoryBox.getSelectedIndex() == 0 || Price.equals("") || Mfg.equals("") || Exp.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter data","Empty Input",2);
        }
        else
        {
            try{
                SerialNumber = Integer.parseInt(SerialNo);
                Mdprice = Integer.parseInt(Price);
                int rowCount = DatabaseTable.getRowCount();
                for(int i = 0; i<rowCount; i++){
                    String SerialNum = (String)DatabaseTable.getValueAt(i,0);
                    if(SerialNo.equals(SerialNum))
                    {
                        JOptionPane.showMessageDialog(this,"Data for this medicine already exits.","Repeated data",1);
                        return;
                    }
                }
                if(!Pattern.compile("[0-9]{4}").matcher(SerialNo).matches())
                {
                    JOptionPane.showMessageDialog(this,"Invalid serial number","Invalid input",0);
                    return;
                }
                dfm.addRow(st);
                MedicineTableData data = new MedicineTableData(SerialNumber, Name, Type, Category, Mdprice, Mfg, Exp);
                Mdata.add(data);
                loadCSV();
            } 
            catch(NumberFormatException nfe){
                JOptionPane.showMessageDialog(this,"Enter the details in correct format","Invalid Input",0);
            }
            
        }
    }//GEN-LAST:event_ButAddActionPerformed
    
    //Exit on Menu ITem
    private void ExitMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuIActionPerformed
        System.exit(0); //TO EXIT THE SYSTEM
    }//GEN-LAST:event_ExitMenuIActionPerformed
    
    
    //Delete button for deleting table data
    private void ButDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButDeleteActionPerformed
        int a = JOptionPane.showConfirmDialog(this,"Are you sure you want to delete the table?","Delete table data",JOptionPane.YES_NO_OPTION);
        if(a == 0){
                DefaultTableModel dfm1 = (DefaultTableModel)DatabaseTable.getModel();
                dfm1.setRowCount(0);
                Mdata.clear();  
        }
    }//GEN-LAST:event_ButDeleteActionPerformed
    
    
    //Sorting button to sort data inside the table
    private void ButSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSortActionPerformed
        selectionSort();
        addSortedData();
    }//GEN-LAST:event_ButSortActionPerformed

    private void PasswordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTxtActionPerformed

    private void UserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTxtActionPerformed

    
    //Log in button 
    private void ButLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLoginActionPerformed
        String Username = UserNameTxt.getText().trim();
        String Password = PasswordTxt.getText().trim();
        if(!Username.isEmpty() && !Password.isEmpty() ){
            if(Username.equals("admin") && Password.equals("admin")){
                FrontFrame.setVisible(false);
                this.setSize(990, 850);
                MainPanel.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this,"Enter correct Log In details","Log In",2);
            }
        }else{
            JOptionPane.showMessageDialog(this,"Enter Log In details","Log In",1);
        }

    }//GEN-LAST:event_ButLoginActionPerformed

    private void TypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeTxtActionPerformed
    
    
    
    //Selection sorting
    public void selectionSort(){
        for(int i = 0; i < Mdata.size()-1; i++)
        {
            int minPos = i;
            for(int j = i +1; j < Mdata.size();j++)
            {
                if(Mdata.get(minPos).getSerialNumTxt() > Mdata.get(j).getSerialNumTxt())
                {
                    minPos = j;
                }
            }
            Collections.swap(Mdata,minPos,i);
        }
    }
    
    
    //Binary searching
    
    public static int binarySearch(ArrayList<MedicineTableData> Mdata, int start, int stop, int search){
        if (start <= stop){
            int middleValue = (start + stop)/2;
            
            if (Mdata.get(middleValue).getPriceTxt() == search){
                    return middleValue;
            }
            else if (Mdata.get(middleValue).getPriceTxt() > search){
                return binarySearch(Mdata, start, middleValue-1, search);
            }
            else{
                return binarySearch(Mdata, middleValue+1, stop, search);
            }
        }
        else{
            return -1;
        }
        
    }
    
    //Adding sorted data in arraylist
    public void addSortedData(){
        DefaultTableModel dtm = (DefaultTableModel) DatabaseTable.getModel();
        dtm.setRowCount(0);
        for(MedicineTableData td: Mdata)
        {
            String values[] = {td.getSN(),td.getNameTxt(),td.getTypeTxt(), td.getCategoryBox(),td.getPrice(),td.getMfgTxt(),td.getExpTxt()};
            dtm.addRow(values);
        }
    }
    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    
    
    //Creating CSV file for data storing 
    public void loadCSV() 
    {
        try {
            File f1 = new File("MedicineData.csv");
            if (!f1.isFile()) 
            {
                f1.createNewFile();
            }
            FileWriter fw = new FileWriter(f1);
            for(MedicineTableData mtd:Mdata)
            {
                String values[] = {mtd.getSN(),mtd.getNameTxt(),mtd.getTypeTxt(),mtd.getCategoryBox(),mtd.getPrice(),mtd.getMfgTxt(),mtd.getExpTxt()};
                for( int i = 0; i < values.length;i++)
                {
                    fw.append(values[i]);
                    if(i == values.length-1)
                    {
                        break;
                    }
                    fw.append(",");
                }   
                fw.append("\n");
            }
            fw.flush();
            fw.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"IO Exception occured");
        }
    }
    
    //Reading the CSV file 
    public void readCSV() {
        try {
            BufferedReader bffr = new BufferedReader(new FileReader("MedicineData.CSV"));
            String row = "";
            while ((row = bffr.readLine()) != null) {
                String Values[] = row.split(",");
                DefaultTableModel dtm = (DefaultTableModel) DatabaseTable.getModel();
                dtm.addRow(Values);
                MedicineTableData data0 = new MedicineTableData(Integer.parseInt(Values[0]), Values[1], Values[2], Values[3],Integer.parseInt(Values[4]),  Values[5], Values[6]);
                Mdata.add(data0);
            }
        } catch (FileNotFoundException fne) {
            JOptionPane.showMessageDialog(this, "File not Found");
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(this, "IOExeption occured");
        } catch (IndexOutOfBoundsException iobe){
            JOptionPane.showMessageDialog(this, "IndexOutOfBoundsException occured");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicineIS().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAdd;
    private javax.swing.JButton ButCategory;
    private javax.swing.JButton ButClear;
    private javax.swing.JButton ButDelete;
    private javax.swing.JButton ButLogin;
    private javax.swing.JButton ButSearchPrice;
    private javax.swing.JButton ButSort;
    private javax.swing.JComboBox<String> CategoryBox;
    private javax.swing.JLabel Categorylbl;
    private javax.swing.JTable DatabaseTable;
    private javax.swing.JMenuItem ExitMenuI;
    private javax.swing.JTextField ExpTxt;
    private javax.swing.JLabel Explbl;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JPanel FrontFrame;
    private javax.swing.JLabel Head1;
    private javax.swing.JLabel Head2;
    private javax.swing.JLabel HeadTitle;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem HelpMenuI;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JLabel Loginlbl;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuBar MenuB;
    private javax.swing.JTextField MfgTxt;
    private javax.swing.JLabel Mfglbl;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JMenuItem OpenMenuI;
    private javax.swing.JPasswordField PasswordTxt;
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JLabel Pricelbl;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JTextField SearchPriceTxt;
    private javax.swing.JTextField SerialNumTxt;
    private javax.swing.JLabel SerialNumlbl;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JTextField TypeTxt;
    private javax.swing.JLabel Typelbl;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JScrollPane database;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
